ARG VERSION=14
FROM node:$VERSION
RUN apt update -y
RUN apt upgrade -y
RUN apt install -y tmux
EXPOSE 3000
ENV abcd=wtf
RUN apt install -y zsh
RUN apt install -y vim
RUN apt install -y neovim
RUN print 'Y\n' | sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
#RUN apt install tmux
#USER node
WORKDIR /morestuff
COPY . .

