version: "3"
services:
  chatapp:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        VERSION: 16
    ports:
      - "3000:3000"
      - "9229:9229"
    #networks: 
    #  - mynet    
    volumes:
      - ..:/chatapp 
    command: /bin/sh -c "while sleep 1000;do :;done"
    depends_on:
      - postgresdb
      - cache
  
  cache:
    image: redis:alpine
    #restart: always
    ports:
      - '6379:6379'
    #command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    command: redis-server --requirepass test1234
    volumes: 
      - cache:/data
  
  postgresdb:  
    image: postgres:alpine
    #command: --default-authentication-plugin=mysql_native_password
    #networks: 
    #  - mynet
    #expose: 
    #   - '3306'
    environment:
      #MYSQL_ROOT_HOST: "%"
      #MYSQL_ROOT_PASSWORD: test1234
      #MYSQL_PASSWORD: test1234
      #MYSQL_DATABASE: test1  
      #MYSQL_USER: mysql1
      POSTGRES_USER: postgres
      POSTGRES_DB: test
      POSTGRES_PASSWORD: test1234
      #mysql user myswl database myswl password etc etc
    ports:
      - "5432:5432"
    volumes:
      - dbstuff1:/var/lib/postgresql/data
      # - dbstuff:/var/lib/mysql

volumes:
  dbstuff1:
  cache:

          #networks:
          # mynet:
